// navigation
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
// home
export const SET_HOVER_WIDTH = 'SET_HOVER_WIDTH';
// form
export const SET_FOCUSED_INPUT = 'SET_FOCUSED_INPUT';
export const CLEAN_FOCUSED_INPUT = 'CLEAN_FOCUSED_INPUT';
export const SET_NAME_INPUT_VALUE = 'SET_NAME_INPUT_VALUE';
export const SET_EMAIL_INPUT_VALUE = 'SET_EMAIL_INPUT_VALUE';
export const SET_NICKNAME_INPUT_VALUE = 'SET_NICKNAME_INPUT_VALUE';
export const SET_PASSWORD_INPUT_VALUE = 'SET_PASSWORD_INPUT_VALUE';
export const VALIDATE_INPUT = 'VALIDATE_INPUT';
// login
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGN_UP_ATTEMPT = 'SIGN_UP_ATTEMPT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
